from paz.models.classification.xception import MiniXceptionFER
from paz.models.detection.haar_cascade import HaarCascadeFrontalFaceDetector
from paz.models.detection.haar_cascade import HaarCascadeEyeDetector
